// <auto-generated />
using System;
using FormulaEngine.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FormulaEngine.Api.Migrations
{
    [DbContext(typeof(FormulaEngineContext))]
    partial class FormulaEngineContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FormulaEngine.Api.Models.Cell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasPrecision(28, 10)
                        .HasColumnType("numeric(28,10)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Key")
                        .IsUnique();

                    b.ToTable("Cells");
                });

            modelBuilder.Entity("FormulaEngine.Api.Models.Dependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FromCellId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToCellId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FromCellId");

                    b.HasIndex("ToCellId");

                    b.HasIndex("WorkspaceId", "FromCellId", "ToCellId")
                        .IsUnique();

                    b.ToTable("Dependencies");
                });

            modelBuilder.Entity("FormulaEngine.Api.Models.Formula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CellId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CellId")
                        .IsUnique();

                    b.ToTable("Formulas");
                });

            modelBuilder.Entity("FormulaEngine.Api.Models.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("FormulaEngine.Api.Models.Cell", b =>
                {
                    b.HasOne("FormulaEngine.Api.Models.Workspace", "Workspace")
                        .WithMany("Cells")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("FormulaEngine.Api.Models.Dependency", b =>
                {
                    b.HasOne("FormulaEngine.Api.Models.Cell", "FromCell")
                        .WithMany("OutgoingDependencies")
                        .HasForeignKey("FromCellId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FormulaEngine.Api.Models.Cell", "ToCellNav")
                        .WithMany("IncomingDependencies")
                        .HasForeignKey("ToCellId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FormulaEngine.Api.Models.Workspace", "Workspace")
                        .WithMany("Dependencies")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromCell");

                    b.Navigation("ToCellNav");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("FormulaEngine.Api.Models.Formula", b =>
                {
                    b.HasOne("FormulaEngine.Api.Models.Cell", "Cell")
                        .WithOne("Formula")
                        .HasForeignKey("FormulaEngine.Api.Models.Formula", "CellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cell");
                });

            modelBuilder.Entity("FormulaEngine.Api.Models.Cell", b =>
                {
                    b.Navigation("Formula");

                    b.Navigation("IncomingDependencies");

                    b.Navigation("OutgoingDependencies");
                });

            modelBuilder.Entity("FormulaEngine.Api.Models.Workspace", b =>
                {
                    b.Navigation("Cells");

                    b.Navigation("Dependencies");
                });
#pragma warning restore 612, 618
        }
    }
}
